/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExpenseCharts: typeof import('./src/components/ExpenseCharts.vue')['default']
    ExpenseList: typeof import('./src/components/ExpenseList.vue')['default']
    ExpensePagination: typeof import('./src/components/ExpensePagination.vue')['default']
    ExpenseSearch: typeof import('./src/components/ExpenseSearch.vue')['default']
    ExpenseStats: typeof import('./src/components/ExpenseStats.vue')['default']
    ExpenseTable: typeof import('./src/components/ExpenseTable.vue')['default']
    ExportButton: typeof import('./src/components/ExportButton.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MarkdownDialog: typeof import('./src/components/MarkdownDialog.vue')['default']
    MessageTip: typeof import('./src/components/MessageTip.vue')['default']
    PredictionDropdown: typeof import('./src/components/PredictionDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpendingLimitDisplay: typeof import('./src/components/SpendingLimitDisplay.vue')['default']
    SpendingLimitSetting: typeof import('./src/components/SpendingLimitSetting.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/TodoList.vue')['default']
  }
}
